#!/bin/bash

# VPS Manager Installation Script
# For Ubuntu 24.04 LTS

set -e

echo "🖥️  VPS Manager Installation"
echo "=============================="
echo ""

# Check if running as root
if [ "$EUID" -eq 0 ]; then 
    echo "❌ Please do not run as root. Run as a regular user with sudo privileges."
    exit 1
fi

# Check Ubuntu version
if ! grep -q "Ubuntu" /etc/os-release; then
    echo "⚠️  Warning: This script is designed for Ubuntu. Proceed anyway? (y/n)"
    read -r response
    if [[ ! "$response" =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

echo "📦 Installing system dependencies..."
sudo apt update
# rsync: server-to-server transfers; sshpass: optional, for password-based SSH auth
# mysql-client: provides mysql/mysqldump for database backup & restore
sudo apt install -y python3 python3-pip python3-venv git rsync sshpass mysql-client

echo ""
echo "📁 Setting up application directory..."
INSTALL_DIR="/opt/vps-manager"

if [ -d "$INSTALL_DIR" ]; then
    echo "⚠️  Directory $INSTALL_DIR already exists. Remove it? (y/n)"
    read -r response
    if [[ "$response" =~ ^[Yy]$ ]]; then
        sudo rm -rf "$INSTALL_DIR"
    else
        echo "Installation cancelled."
        exit 1
    fi
fi

sudo mkdir -p "$INSTALL_DIR"
sudo chown "$USER:$USER" "$INSTALL_DIR"

echo ""
echo "📥 Copying files..."
cp -r ./* "$INSTALL_DIR/"
cp ./.env.example "$INSTALL_DIR/" 2>/dev/null || true  # cp ./* skips dotfiles
cd "$INSTALL_DIR"

echo ""
echo "🐍 Creating Python virtual environment..."
python3 -m venv venv
source venv/bin/activate

echo ""
echo "📚 Installing Python dependencies..."
pip install --upgrade pip
pip install -r requirements.txt

echo ""
echo "🔐 Configuring login credentials..."
ENV_FILE="$INSTALL_DIR/.env"
if [ -f "$ENV_FILE" ]; then
    echo "  An existing .env was found — keeping your current credentials."
else
    read -r -p "  Admin username [admin]: " ADMIN_USER
    ADMIN_USER="${ADMIN_USER:-admin}"

    read -r -s -p "  Admin password (leave blank to auto-generate): " ADMIN_PASS
    echo ""
    GENERATED_PASS=""
    if [ -z "$ADMIN_PASS" ]; then
        ADMIN_PASS="$(python3 -c 'import secrets; print(secrets.token_urlsafe(16))')"
        GENERATED_PASS="$ADMIN_PASS"
    fi

    SECRET_KEY="$(python3 -c 'import secrets; print(secrets.token_hex(32))')"

    # printf %s writes the values literally (no shell/backslash interpretation)
    {
        printf '# VPS Manager configuration (generated by install.sh)\n'
        printf 'ADMIN_USERNAME=%s\n' "$ADMIN_USER"
        printf 'ADMIN_PASSWORD=%s\n' "$ADMIN_PASS"
        printf 'SECRET_KEY=%s\n' "$SECRET_KEY"
    } > "$ENV_FILE"
    chmod 600 "$ENV_FILE"

    echo "  ✅ Credentials written to $ENV_FILE (permissions 600)."
    if [ -n "$GENERATED_PASS" ]; then
        echo ""
        echo "  ⚠️  Auto-generated password (save it now, it is not shown again):"
        echo "        $GENERATED_PASS"
    fi
fi

echo ""
echo "✅ Installation complete!"
echo ""
echo "To start VPS Manager:"
echo "  cd $INSTALL_DIR"
echo "  source venv/bin/activate"
echo "  python app.py"
echo ""
echo "Then access at: http://YOUR_SERVER_IP:5000"
echo ""
echo "⚠️  SECURITY NOTES:"
echo "  - Login is enabled; credentials are stored in $INSTALL_DIR/.env"
echo "  - To change them later, edit that file and restart the app"
echo "  - Run behind HTTPS and restrict port 5000 with a firewall"
echo "  - See SECURITY.md for hardening recommendations"
echo ""
